Repository suchitadoshi1987/related-files-hopper, pull requests merged in 2020-01, with the labels that each got.

#7 Add support for user provided custom glob patterns and extensions option
  README.md
  extension.js
  package.json
  utils/helper.js
Labels: documentation, enhancement

#9 Remove / in front of c: for Windows
  extension.js
Labels: bug

#10 Add functionality for allowing users to specify their own ignore patterns
  README.md
  extension.js
  package.json
Labels: enhancement
